### ISSUE TITLE
Checkbox toggling inconsistent in example

### ISSUE THREAD

**Issue by yroc92** [diprokon/ng-table-virtual-scroll#1]
I'm amazed with your directive! It's a bummer the Angular team is dragging their feet with https://github.com/angular/components/issues/10122.

In the example for "Table with filter, sort and selection" in the live demo, the checkboxes function very inconsistently. For example, try checking each row, one at time and occasionally toggling the header checkbox. 

I'm not sure whether this broken functionality is reflective of the virtual-scroll implementation or just a bug with how checkbox states are managed (hopefully the latter, as I could really use the checkbox functionality!).

This was noticed in Chrome 78.0.3904.97.

**Comment by diprokon** [comment]
Hi!
Thanks, I really glad that this directive helps someone except me!

You were right - there was an issue with change detection. I hope, my fix will help, please check the last version.

Thanks for helping to find it :)
