### ISSUE TITLE
Sticky footer not working

### ISSUE THREAD

**Issue by mpo-dev** [diprokon/ng-table-virtual-scroll#101]
A sticky footer does not work, it disappears when scrolling down to only appear on the bottom at the table again.

**Comment by Mintenker** [comment]
I second this, same issue happening to me.

**Comment by diprokon** [comment]
Can you share working example with the issue?

**Comment by yitzchokneuhaus1** [comment]
@diprokon Can you provide a working stackblitz page using this package. I believe I can reproduce it

**Comment by ShimonLeb** [comment]
I think this line should be changed
https://github.com/diprokon/ng-table-virtual-scroll/blob/6ac7e09e2ad6095c821a3ec046d361c4585b924c/projects/ng-table-virtual-scroll/src/lib/table-item-size.directive.ts#L34
to
`const stickyFooterSelector = '.mat-footer-row .mat-table-sticky, .mat-footer-row.mat-table-sticky, .cdk-footer-row .cdk-table-sticky, .cdk-header-row.cdk-table-sticky';`
