### ISSUE TITLE
Angular/Material 15, sticky header does not work

### ISSUE THREAD

**Issue by joerggross** [diprokon/ng-table-virtual-scroll#111]
Angular/Material15 based on MDC introduces new css class (*_mdc_*). As these classes are used in css-selectors the sticky header does not work anymore. 

Already @TobiDimmel posted this problem in this thread: https://github.com/diprokon/ng-table-virtual-scroll/issues/107. But this thread is closed.

Is there any update planned?

**Comment by TobiDimmel** [comment]
Added a PR with the fix (see #112).

**Comment by diprokon** [comment]
Yep, there are problems with Material 15 and I'm already fixing it

**Comment by danielfnz** [comment]
@diprokon Any progress on this?

**Comment by samitjainmca** [comment]
Issue still persist with ng-table-virtual-scroll v15

**Comment by rvalimaki** [comment]
> Issue still persist with ng-table-virtual-scroll v15. Is there a plan to provide a fix soon?

I can confirm that 1.5.0 release does not fix sticky header/footer issues with Angular Material 15. Also I haven't found a workaround for the time being.

**Comment by rvalimaki** [comment]
I can also confirm that adding mdc based css selectors fixes the problem. I guess that non-mdc css selectors are relevant only for legacy table support.

**Comment by gabrielnemeth** [comment]
@rvalimaki what do you mean by adding mdc based selectors? I don't use any CSS selectors in my code but the header is still broken even after the latest update.

**Comment by alvipeo** [comment]
I have the same problem - header just moves down outside of viewport after some scrolling. Is there anything I can do with it?

**Comment by diprokon** [comment]
Hi all.
Sorry for such delay
Update for the ng15 is in progress and new version with fixes will be soon
