### ISSUE TITLE
Issue with filtered data

### ISSUE THREAD

**Issue by engzizo79** [diprokon/ng-table-virtual-scroll#15]
When data is filtered the scrolling behaviour is not changed and still tries to scroll through all data records.

For example: Data has 100 records. Filtered Data has only 10 records. It is still possible to scroll further than the availabla 10 records, which also breaks the sticky header.

I think filtereddata should be used instead of data, since it is also that what is displayed.

**Comment by celian-garcia** [comment]
True, and easily reproducible in the examples page https://diprokon.github.io/ng-table-virtual-scroll/#/examples

**Comment by duxor** [comment]
Same for me
