### ISSUE TITLE
Triggering scroll by code does not work.

### ISSUE THREAD

**Issue by BenJanaka** [diprokon/ng-table-virtual-scroll#16]
I want to trigger the scroll of the CdkVirtualScrollViewport by calling scrollToIndex.

Expected behaviour:
 - The virtual scroll viewport scrolls to the passed index parameter.

Actually nothing happens. 

Worked around the issue by using the scrollBy function of the viewport nativeElement. But still, the issue remains.

**Comment by duxor** [comment]
@BenJanaka yeah, something is wrong with `scrollToIndex` method but `scrollToOffset` should work.

In my case, there is a bug when I have `scrollToOffset` but without `smooth` option - sticky header is not at the top of the table.

**Comment by diprokon** [comment]
Fixed in 1.3.2
