### ISSUE TITLE
Laggy loading 

### ISSUE THREAD

**Issue by victoriaunizhona** [diprokon/ng-table-virtual-scroll#20]
If there are a lot of  elements and the table is complex one - everything is loading even slower than without virtual scroll.

"@angular/cdk": "^7.2.0",
"@angular/material": "^7.2.0",
"ng-table-virtual-scroll": "^1.3.1",

Browsers: the most up-to-date Chrome and Mozila

**Comment by AmbroiseVuaridel** [comment]
Maybe another missing module ? Have you checked you have all the modules from app module and example module imported ?

I have a 15s improvement on a 16s loading without virtual scroll on a large table with complex rows.

**Comment by AmbroiseVuaridel** [comment]
Can you provide a stackblitz example ?

**Comment by victoriaunizhona** [comment]
@AmbroiseVuaridel  Unfortunately, cannot provide example as it is under NDA. 

All the modules needed for work are added - no issues during testing. 

I have import { TableVirtualScrollModule } from 'ng-table-virtual-scroll';
and import {ScrollingModule} from "@angular/cdk/scrolling";

What modules are you referring to?
