### ISSUE TITLE
Scroll issue with solution

### ISSUE THREAD

**Issue by DimitriLib** [diprokon/ng-table-virtual-scroll#25]
Using directive with datasource, virtual scroll works great. But experiencing issue with keyboard navigation (Arrow Up/Arrow Down) and scrolling of the contents.
We have mat table with sticky headers.
To reproduce,  first scroll down with arrow keys so first 5 rows would disappear from the viewport, then start scrolling up. Once top visible row reached, contents is not scrolled, but almost feels like it counts header row as a part of the visible scroll area. It feels that scroll is one row behind because of counting of the header row as a part of visible scroll.

**Comment by diprokon** [comment]
Looks like it virtual scroll issue. I found this: https://github.com/angular/components/issues/14765
