### ISSUE TITLE
If Table is rendered but not visible then the grid wont scale correctly

### ISSUE THREAD

**Issue by blogcraft** [diprokon/ng-table-virtual-scroll#26]
In a Component have 3 tabs.
In each tab I have a virtual Scroll table and are loaded when the component loads (ngOnInit).

As just 1 table is visible at a time, the grids that are hidden appear collapsed (only showing header and footer) when changing to it's tab. And only show themselves when resizing the window.

**Comment by Markus-Ende** [comment]
Have the same issue. A work-around for me was, to dispatch a resize event after setting a new data source:

```ts
setTimeout(() => window.dispatchEvent(new Event('resize')), 0);
```

**Comment by blogcraft** [comment]
The problem with that is that it will re render the charts I use in the same window and is a very big hit in performance.

**Comment by diprokon** [comment]
Please, check this [comment](https://github.com/diprokon/ng-table-virtual-scroll/issues/7#issuecomment-586589716)
