### ISSUE TITLE
Scrolling issue when using sticky header + sticky column

### ISSUE THREAD

**Issue by mrandreev** [diprokon/ng-table-virtual-scroll#28]
When you try to use a sticky header with sticky columns there is some issue when you try to scroll up in the middle of the table. But it's ok when you try to use it separately.

It reproducible in [Live Demo](https://diprokon.github.io/ng-table-virtual-scroll), just need to add 'sticky: true' to the header.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/19778013/84771173-9b866500-afe1-11ea-83d8-acc43ded6c07.gif)

**Comment by diprokon** [comment]
Fixed in 1.3.3
