### ISSUE TITLE
scrollbar jerks up and down

### ISSUE THREAD

**Issue by rsivan** [diprokon/ng-table-virtual-scroll#30]
When dragging the scrollbar from the top down, at first the table rows scroll as expected, but when I reach about 70-80% down the scrollbar starts jerking up and down.
Note: the table has variable row heights, perhaps that is what causes the jerk?
See attached recording.

[scrpll3.mov.zip](https://github.com/diprokon/ng-table-virtual-scroll/files/4806440/scrpll3.mov.zip)

**Comment by rsivan** [comment]
Interesting, setting 'tvsItemSize' with no value fixes the issue!!!

**Comment by luckashenri** [comment]
The same is happening to me now. @rsivan fix didn't work for me.. Any ideas?
