### ISSUE TITLE
Custom sorting and filtering method

### ISSUE THREAD

**Issue by Vincentspy** [diprokon/ng-table-virtual-scroll#34]
Custom sorting and filtering methods are not working with this project

@ViewChild(MatSort, {}) sort: MatSort;

this.dataSource.sortingDataAccessor = ...
this.dataSource.filterPredicate = ...

then
this.dataSource.sort = this.sort;
this.dataSource.filter = filterValue;

**Comment by diprokon** [comment]
It works correct for me
@Vincentspy can you provide an example with the issue?
