### ISSUE TITLE
Scroll with sticky headers

### ISSUE THREAD

**Issue by teland94** [diprokon/ng-table-virtual-scroll#39]
Sticky header dissappearing while you scroll items. This issue is reproducing while you scroll items on your demo page with sticky headers! Tested with Chrome Mobile browser. Will you fix it?

**Comment by kevinya** [comment]
I created a PR to correct that : #44

**Comment by diprokon** [comment]
Can you reproduce it after 1.3.4?

**Comment by teland94** [comment]
Yes, it works, thank you.
