### ISSUE TITLE
get and set declared in typescript interface dataLength property

### ISSUE THREAD

**Issue by azulay7** [diprokon/ng-table-virtual-scroll#41]
ERROR in node_modules/ng-table-virtual-scroll/lib/fixed-size-table-virtual-scroll-strategy.d.ts(20,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/ng-table-virtual-scroll/lib/fixed-size-table-virtual-scroll-strategy.d.ts(21,9): error TS1086: An accessor cannot be declared in an ambient context.

Failed in runtime.
"@angular/cli": "~7.1.4",
"typescript": "^3.1.6",

I tried to update to tsc 3.8.3 but my angular cli return an error
ERROR in The Angular Compiler requires TypeScript >=3.1.1 and <3.2.0 but 3.8.3 was found instead.

I can't upgrade at this moment.

**Comment by hakimio** [comment]
That seems to be more of a problem on your end because of incompatible TS version than a bug in this project.

**Comment by vvarelasalichs** [comment]
> ERROR in node_modules/ng-table-virtual-scroll/lib/fixed-size-table-virtual-scroll-strategy.d.ts(20,9): error TS1086: An accessor cannot be declared in an ambient context.
> node_modules/ng-table-virtual-scroll/lib/fixed-size-table-virtual-scroll-strategy.d.ts(21,9): error TS1086: An accessor cannot be declared in an ambient context.
> 
> Failed in runtime.
> "@angular/cli": "~7.1.4",
> "typescript": "^3.1.6",
> 
> I tried to update to tsc 3.8.3 but my angular cli return an error
> ERROR in The Angular Compiler requires TypeScript >=3.1.1 and <3.2.0 but 3.8.3 was found instead.
> 
> I can't upgrade at this moment.

I had same problem (with angular 7) and I just install "ng-table-virtual-scroll" version "1.3.1" instead of last version.
With this, it works for me.

**Comment by diprokon** [comment]
As I understand, the problem is in your versions. You need to update angular version, or use `"skipLibCheck": true` in tsconfig.json "compilerOptions" ([link](https://stackoverflow.com/a/60294898))

**Comment by azulay7** [comment]
@diprokon you nailed it. Thanks!
