### ISSUE TITLE
not an issue - a suggestion :)

### ISSUE THREAD

**Issue by yuda85** [diprokon/ng-table-virtual-scroll#45]
I needed to use async data for the table and couldn't get the package to work properly so I took it into the project and basically had to change just 1 thing that made it work great

on table-item-size.directive.ts : 
instead of 
```
  @ContentChild(MatTable, { static: **true** })
  table: MatTable<any>;
```

```
  @ContentChild(MatTable, { static: **false** })
  table: MatTable<any>;
```

**Comment by diprokon** [comment]
Changed in 1.3.4
