### ISSUE TITLE
Multiple Sticky Header Rows

### ISSUE THREAD

**Issue by niklashNH** [diprokon/ng-table-virtual-scroll#48]
Hey there,

when using multiple sticky header rows the first row gets hidden under the second row. Seems like a duplicate of [Issue #21](https://github.com/diprokon/ng-table-virtual-scroll/issues/21#issue-601191022).
Im on version 1.3.4 with @angular/cdk 10.2.7, so the fix mentioned in #21 should already be applied. But it still does not work properly.

Any advice on this?

Example can be found here: [StackBlitz](https://stackblitz.com/edit/angular-ivy-y8k9jz?file=src/app/app.component.html)

**Comment by RicardoWillemsen** [comment]
Any updates on this? I'm running into the same issue. One sticky header works fine, two don't.
