### ISSUE TITLE
Issue when table has borders;

### ISSUE THREAD

**Issue by red17electro** [diprokon/ng-table-virtual-scroll#5]
Hi!

Try to set the border & border-radius on the header & for cells of the table.
Then, if you scroll, you will notice that the border from the cell is visible and overlapping with the header, which should not be the case (basically, it forces you to avoid using border-radius on the header). 
Please, have a look at the screenshot as well. The green areas are the ones from cells that overlap at the corners of rounded header.

Best, Server.

<img width="985" alt="Screenshot 2020-01-16 at 15 17 57" src="https://user-images.githubusercontent.com/16454623/72532293-70052000-3873-11ea-9e75-24722c3e9681.png">

**Comment by diprokon** [comment]
Hi!

Can you provide some code sample what illustrate this issue?
