### ISSUE TITLE
When used with inline table form elements error is reset after removed from view

### ISSUE THREAD

**Issue by galwa** [diprokon/ng-table-virtual-scroll#52]
I am using virtual scroll in combine with multiple mat-form-field elements inline the cells

When a formControl have an error it is displayed but when scrolling it out of view and coming back the error is reset to null in the control - could it be related to default caching strategy ?

**Comment by diprokon** [comment]
When you scrolling, all elements, which are not in view, are destroyed. It is the feature of virtual scroll.
Maybe, when your formControl is destroyed and recreated, it forgets about the error?
