### ISSUE TITLE
Couldn't initialise the table with data

### ISSUE THREAD

**Issue by rohitattaluri552** [diprokon/ng-table-virtual-scroll#53]
Hi all, 

I was trying to figure a way to implement virtual scroll and came here to use it.

Installed the plugin from **Npm** and tried fulfilling my requirement. 

But at the initially stage it self, i couldn't assign my data to **dataSource** as show in the example.

FYI, here I'm attaching my code snippets screenshots as well. Any suggestions will be appreciated.  

<img width="854" alt="Screenshot 2021-01-15 at 7 03 35 PM" src="https://user-images.githubusercontent.com/61145279/104733446-b6ca7600-5764-11eb-8584-f3ccd95d6bbb.png">
<img width="854" alt="Screenshot 2021-01-15 at 7 03 44 PM" src="https://user-images.githubusercontent.com/61145279/104733485-c34ece80-5764-11eb-9534-6acbf8b07da0.png">
<img width="1413" alt="Screenshot 2021-01-15 at 7 06 44 PM" src="https://user-images.githubusercontent.com/61145279/104733539-dc577f80-5764-11eb-965a-825d8ec1a22a.png">

**Comment by MiszczProgramowania** [comment]
same issue i have

**Comment by Elias177** [comment]
After hours of testing and changing stuff around. I finally fixed it.

Make sure you include **ScrollingModule** in your module imports

**Comment by sushil1991** [comment]
I am also facing the same issue. When can we have a fix for it.

**Comment by wellwind** [comment]
Same issue here, after importing `ScrollingModule` can fix.

I think it should be added into document.

**Comment by diprokon** [comment]
This library is only to help `cdk-virtual-scroll-viewport` and `mat-table` to communicate properly. It is expected, that you configure those part properly.
Also, there is a note about it in the documentation. Now I added the required modules names, so I hope it will helps
