### ISSUE TITLE
Scrolling issue when using sticky column with angular 10

### ISSUE THREAD

**Issue by mrandreev** [diprokon/ng-table-virtual-scroll#58]
Hey there, 

When we upgrade to angular 10 we found a similar bug we had before: https://github.com/diprokon/ng-table-virtual-scroll/issues/28

When you try to use sticky columns there is some issue when you try to scroll up in the middle of the table.

It reproducible in [Live Demo](https://diprokon.github.io/ng-table-virtual-scroll), just need to update to angular 10

![scroll-bag](https://user-images.githubusercontent.com/19778013/106746498-4f993680-662b-11eb-97c9-7474a81159b1.gif)

**Comment by voznik** [comment]
FYI, in Live Demo this bug reproduces only for scrolling up. scrolling down acts as expected

**Comment by mrandreev** [comment]
Hey there, it still reproduces on demo example with sticky columns:
https://diprokon.github.io/ng-table-virtual-scroll/examples

**Comment by MaximeKoitsalu** [comment]
@mrandreev We are also having the same issue. How exactly did you reproduce it and have you found any workaround?
