### ISSUE TITLE
Issue with dynamic spanrow

### ISSUE THREAD

**Issue by simyco** [diprokon/ng-table-virtual-scroll#6]
Hello,
great work, i really appreciate this lib!
i'm just facing some issuee when using in combo with dynamic spanrow
When using a code like this:
```
<td
              mat-cell
              *matCellDef="let element; let i = index"
              [style.padding-left]="'5px'"
              [style.padding-right]="'5px'"
              [style.display]="getRowSpan(col, i) ? '' : 'none'"
              [attr.rowspan]="getRowSpan(col, i)"
            >
              <div [innerHTML]="element[col]"></div>
            </td>

```
```
spanRow(key: any, accessor: any) {
    for (let i = 0; i < this.DATA.length; ) {
      const currentValue = accessor(this.DATA[i]);
      let count = 1;

      for (let j = i + 1; j < this.DATA.length; j++) {
        if (currentValue !== accessor(this.DATA[j])) {
          break;
        }

        count++;
      }

      if (!this.spans[i]) {
        this.spans[i] = {};
      }

      this.spans[i][key] = count;
      i += count;
    }
  }

  getRowSpan(col: string | number, index: string | number) {
    return this.spans[index] && this.spans[index][col];
  }
```

The result in some columns is broken:
<img width="1155" alt="Screenshot 2020-01-25 at 09 27 17" src="https://user-images.githubusercontent.com/13273671/73118478-e92c0380-3f54-11ea-9858-a46106af5633.png">
(Buon 1980 is not spanned like the others, when not using this lib is working right)

Thanks again!

**Comment by diprokon** [comment]
Hi!
I'm not sure, that your issue is related to this lib. Did you fix it already?
If not, can you ,please, provide the full html/ts code for the component with table?

**Comment by scribter** [comment]
Hi,
same problem when I wanne change the height with``[style.height.px]`` dynamically.
