### ISSUE TITLE
Add support also to CDK table

### ISSUE THREAD

**Issue by asaf11108** [diprokon/ng-table-virtual-scroll#79]
Currently the library support only Mat table. Please add support to CDK table.

Note:
1. ContentChild of mat table in table-item-size.directive.ts, [link](https://github.com/diprokon/ng-table-virtual-scroll/blob/920dc9f7320e1884da41577a68e9585013e67285/projects/ng-table-virtual-scroll/src/lib/table-item-size.directive.ts#L65).
2. css selectors in table-item-size.directive.ts, [link](https://github.com/diprokon/ng-table-virtual-scroll/blob/920dc9f7320e1884da41577a68e9585013e67285/projects/ng-table-virtual-scroll/src/lib/table-item-size.directive.ts#L23).

**Comment by tamascsaba** [comment]
@diprokon it would be really great to support `cdk-table` as well. Thank you 👍

**Comment by diprokon** [comment]
Hi!
I'm preparing the solution for this issue. Probably will be in the next release

**Comment by anschm** [comment]
Hey diprokon! Thanks, that sounds good! Do you have a idea when that will be available?

**Comment by tamascsaba** [comment]
@diprokon thank you man 👍
