### ISSUE TITLE
Ivy support

### ISSUE THREAD

**Issue by leomayer** [diprokon/ng-table-virtual-scroll#80]
When I launch the application with Angular 13 I get

```
⠙ Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:
- ng-table-virtual-scroll [es2015/esm2015] (git://github.com/diprokon/ng-table-virtual-scroll.git)
Encourage the library authors to publish an Ivy distribution.
```

Any plans to fix this?

**Comment by blogcraft** [comment]
Angular 13 support would be nice.

**Comment by SerkanSipahi** [comment]
@leomayer It still works properly? It's just this message, right?

**Comment by leomayer** [comment]
To my understanding yes - didn't see any side effect or anything which won't work.

**Comment by SerkanSipahi** [comment]
@diprokon any updates/infos?

**Comment by blogcraft** [comment]
Guess this library is dead.

**Comment by diprokon** [comment]
Hi guys
Sorry for such delay
All was ok - it was just the message

I added support of ng13 in 1.4.0. It's not showing the message now

**Comment by SerkanSipahi** [comment]
Thanks.
