### ISSUE TITLE
New fork created with Ivy support

### ISSUE THREAD

**Issue by santoshyadavdev** [diprokon/ng-table-virtual-scroll#86]
Hey Everyone, 
If you are planning to use this one with Angular 13 support and Ivy compatible, use

- https://www.npmjs.com/package/ngx2-table-virtual-scroll
- npm i ngx2-table-virtual-scroll 
- version  13.0.0

I am more than happy to keep the fork up to date and if author wants I am happy to takeover this one and maintain.

**Comment by diprokon** [comment]
Hi @santoshyadavdev!
I'm already working on Ivy support and it will be provided ASAP

**Comment by diprokon** [comment]
Updated in 1.4.0

**Comment by santoshyadavdev** [comment]
Thank you this was quick thanks a lot :)
