### ISSUE TITLE
Observable DataSource

### ISSUE THREAD

**Issue by riwos** [diprokon/ng-table-virtual-scroll#9]
Hi,

I have question how use your directive with Observable ??

I know when you want to use Observable data source you have to define your own class like below:

```
export class SampleDataSource extends DataSource<T> {	
  constructor() {	
    super();	
  }	

  connect(collectionViewer: CollectionViewer): Observable<T[]> {	
    return Observable<T[]>();	
  }	

  disconnect(collectionViewer: CollectionViewer): void {}	
}
```

How to apply in your directive ?? 
Does your directive support async pipe ??

Maybe I have missed something but if you could give me example I will appreciate it :)

**Comment by riwos** [comment]
One more question..

Does it possible to control how much rows are rendered on html.

<img width="307" alt="Screenshot 2020-02-18 at 21 46 48" src="https://user-images.githubusercontent.com/684729/74780912-733b6380-5298-11ea-9926-8dfba55d2ee5.png">

For example. I would like only render 5 rows. I am lost today..

Thanks for any reply :)

**Comment by riwos** [comment]
Hi @diprokon 

I have fixed the second question :) For tabs you must configure some things and consider again.

Before my changes when you load data first time you see something like this: 
![Screenshot_2](https://user-images.githubusercontent.com/684729/74824233-e62bf500-52ff-11ea-8b01-00a6e4e7c808.png)

It means the browser tries render all rows and that could be stuck the UI and freeze screen for a couple of seconds..

Then I have applied code:

```
 const start = 0;
 const end = 10;
 this.viewport.setRenderedRange({start, end});
```

on "check()" method and then you have:
![Screenshot_3](https://user-images.githubusercontent.com/684729/74824520-32773500-5300-11ea-88bc-270d583d4744.png)

and this is exactly what I wanted to achieve :)

**Comment by diprokon** [comment]
> Hi,
> 
> I have question how use your directive with Observable ??
> 
> I know when you want to use Observable data source you have to define your own class like below:
> 
> ```
> export class SampleDataSource extends DataSource<T> {	
>   constructor() {	
>     super();	
>   }	
> 
>   connect(collectionViewer: CollectionViewer): Observable<T[]> {	
>     return Observable<T[]>();	
>   }	
> 
>   disconnect(collectionViewer: CollectionViewer): void {}	
> }
> ```
> 
> How to apply in your directive ??
> Does your directive support async pipe ??
> 
> Maybe I have missed something but if you could give me example I will appreciate it :)

With the directive you can only use the TableVirtualScrollDataSource. It can be created or extended - the same as MatTableDataSource.
The easy way to use observable, is to update data: `source.subscribe(data => dataSource.data = data);`
